jobs:
  - name: box-man-1
    type: manifest
    steps:
      - GET: box-sn
      - GET: trigger-dv-man

  - name: ddc-upgrade-deploy-1
    type: ddcDeploy
    steps:
      - GET: box-man-1
      - GET: env-ddc
