jobs:
  - name: box-man
    type: manifest
    steps:
      - GET: box-sn
      - GET: trigger-dv-man

  - name: ddc-upgrade-deploy
    type: ddcDeploy
    steps:
      - GET: box-man
      - GET: env-ddc
