jobs:
  - name: box-man
    type: manifest
    steps:
      - GET: box-sn
      - GET: trigger-dv-man

  - name: dcl-upgrade-deploy
    type: dclDeploy
    steps:
      - GET: box-man
      - GET: dcl-cluster
